import {utilService} from '../../../services/util.service.js';

export const dummyDataService = {
  getDummyEmails,
};

const DUMMY_EMAILS = [
  //INBOX
  {
    id: utilService.makeId(),
    subject: 'Hey Check It Out!',
    body: `Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
       Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.`,
    isRead: false,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'daniel@hotmail.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Quizz for dummies',
    body: `Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim.

        Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'gameQuizz@walla.com',
    status: 'inbox',
    isStarred: true,
  },
  {
    id: utilService.makeId(),
    subject: 'You have a delivery update',
    body: `Hi yuval shai,

        Order 3014758266086439 has a delivery update. You can view the shipping status on our website.

        If you have any questions, please let us know!`,
    isRead: false,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'transaction@AliExpress.com',
    status: 'inbox',
    isStarred: true,
  },
  {
    id: utilService.makeId(),
    subject: 'אישור הזמנה',
    body: `תודה על הזמנתך ביס פלאנט חיפה.


        איסוף הכרטיסים:
        
        1. במידה ובחרת בכרטיס אלקטרוני, יש להציג את הכרטיס, המצורף למייל זה, בעמדת הסדרן בכניסה.
        2. במידה ובחרת באפשרות איסוף הכרטיסים בקולנוע, ניתן להדפיסם בעמדות שירות העצמי בקולנוע באמצעות מספר ההזמנה שלך.
        3. במידה ורכשת כרטיס בהנחה (אזרח ותיק/ סטודנט/ חייל/ שוטר וכו') יש לאסוף את הכרטיסים בקופות הקולנוע, בהצגת תעודת הזכאות.`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'noreply@yesplanet.co.il',
    status: 'inbox',
    isStarred: true,
  },
  {
    id: utilService.makeId(),
    subject: 'Pango FeedBack',
    body: `He lay on his armour-like back, and if he lifted his head a little he 
        could see his brown belly, slightly domed and divided by arches into 
        stiff sections.`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'noreply@Pango-Service.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Lets do it',
    body: `My man! You gave them proof that there was something bigger and scarier to unite against, you little idiot! They would have gone back into the Dark Ages for a couple of generations, but instead, they dedicated themselves into making universe-destroying, un-thought-out technology like time travel all so they could try to kill a little shitsack on Earth who couldn't let a dead snake be dead even after it bit his ankle! What, I'm gonna touch it, and you're gonna tell me it's an alien dick or something? Oh god, oh, I blame myself. Oh, what a tragedy. Oh, well, he's bones now. I guess all debts are paid.`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'Rick&Morty@gmail.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Work brief',
    body: `This was not according to brief thats not what i saw in my head at all. What is lorem ipsum? why is the text in spanish? can it handle a million in one go. I have an awesome idea for a startup, i need you to build it for me. Try making it a bit less blah we are a non-profit organization. We are your relatives. Labrador the target audience is makes and famles aged zero and up can you help me out? you will get a lot of free exposure doing this.`,
    isRead: false,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'Amdocs@amdocs.com',
    status: 'inbox',
    isStarred: true,
  },
  {
    id: utilService.makeId(),
    subject: 'HEISENBERG is wrong',
    body: `This is glass grade. I mean, you got... Jesus, you got crystals in here 2 inches, 3 inches long. This is pure glass. You're a damn artist! This is art, Mr. White! Yeah, that's the thing, y'know? Your scumbag brother-in-law took my rainy day fund. Oh yeah. And tell that douche bag brother-in-law of yours to go towards the light.`,
    isRead: false,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'Jesse@BreakingBad.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'My fellow student',
    body: `I figured I could cut classes for the rest of the semester and he couldn't flunk me as long as I, you know, made the thing. So I finished it in a couple days. And it looked pretty lame, but it worked. You know, for putting in or whatnot. So when I showed it to Mr. Pike for my grade, he looked at it and said: 'Is that the best you can do?' `,
    isRead: false,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'Hank@hotmail.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Tesla Trials Dogecoin',
    body: `Elon Musk recently tweeted the company would accept Dogecoin as payment for merchandise. 
        DOGE briefly traded 27% higher after the announcement.`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'BinanceUpdates@binance.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'GlassDoor new jobs and reviews',
    body: `	To see jobs and company updates relevant to your job.
        New Glassdoor Reviews`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'Glassdoor@glassdoor-service.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'DropBox',
    body: `You're missing the point Morty. Why would he drive a smaller toaster with wheels? I mean, does your car look like a smaller version of your house? No. And there's no evidence that a Latino student did it. This is because you give Morty Smith bad grades, bitch! The algorithm learns your preferences better that way. Plus, if you get in kind of a cool enough relationship, you can sort of follow each other and check out each other's kinks, you know?`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'DropBox@drop-service.com',
    status: 'inbox',
    isStarred: true,
  },
  {
    id: utilService.makeId(),
    subject: 'I finally did it',
    body: `I am Mr. Booby Buyer. I'll buy those boobies for 25 schmeckles! Holy crap, Morty, run! Run for your life, Morty, run! I-I've never seen that thing before in my life, Morty, I don't even know what the hell it is! We-we gotta get out of here, Morty, it's gonna kill us! We're gonna die, Morty! We're gonna die! Whoa, spoilers! I'm a whole season behind. Oh boy, so you actually learned something today? What is this? Full House? I was living in the moment all day, and it kept getting me killed by Nazis. I think you need to think ahead and live in the moment.`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'MrBooby@gmail.com',
    status: 'inbox',
    isStarred: true,
  },
  {
    id: utilService.makeId(),
    subject: 'Order to Haifa',
    body: `I'd like to order one large sofa chair with extra chair please. high chair, no no no recliner... and wheelchair on half. Haha god-damn! Dont look at me! That guy over there roped me into this. God? God's turning people into insect monsters Beth. I'm the one beating them to death. Thank me.`,
    isRead: false,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'Matan@gmail.com',
    status: 'inbox',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'The game is over',
    body: `The game has changed. The word is out. And you... are a killer. Apparently it's all over town. Somebody crossed you, you got angry, you crushed their skull with an ATM machine. Who cares! Just as long as it's our competitors who believe it and not the police. `,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'GusFring@gmail.com',
    status: 'inbox',
    isStarred: false,
  },
  // draft
  {
    id: utilService.makeId(),
    subject: 'Student loans meeting',
    body: `	High turnaround rate optimize for search and we've got kpis for that. Usabiltiy let's put a pin in that pre launch or can we jump on a zoom so form without content style without meaning nor moving the goalposts. Time vampire pull in ten extra bodies to help roll the tortoise, nor get six alpha pups in here for a focus group, nor dear hiring manager: powerpoint Bunny reinvent the wheel. Today shall be a cloudy day, thanks to blue sky thinking, we can now deploy our new ui to the cloud . Quick-win workflow ecosystem. Get six alpha pups in here for a focus group put a record on and see who dances. No need to talk to users, just base it on the space calculator dear hiring manager:. Forcing function blue sky thinking, so they have downloaded gmail and seems to be working for now or horsehead offer, nor obviously so we should leverage existing asserts that ladder up to the message this medium needs to be more dynamic.`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yvc@EmekYezreel.ac.il',
    from: 'yuval@Appsus.com',
    status: 'draft',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Hyundai veloster insurance',
    body: `I know you've made thirty iterations but can we go back to the first one that was the best version I have printed it out, but the animated gif is not moving. Can you rework to make the pizza look more delicious there is too much white space nor can you please send me the design specs again? yet make it pop or we need more images of groups of people having non-specific types of fun. Thanks for taking the time to make the website, but i already made it in wix. Can you please change the color theme of the website to pink and purple?`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'migdal@service.com',
    from: 'yuval@Appsus.com',
    status: 'draft',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Funny Joke',
    body: `My name is Slip- Slippery Stair. I'll take ya down there for 25 shmeckels! Why is "lesbian" part of her job title? Principal Vagina here, don't let the name fool you; I'm very much in charge. Reminding you that tonight is our annual flu season dance. I don't know how many times I have to say this, but if you have the flu, stay home. The flu season dance is about awareness, not celebration. You don't bring dead babies to Passover. The algorithm learns your preferences better that way. Plus, if you get in kind of a cool enough relationship, you can sort of follow each other and check out each other's kinks, you know?`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'idan@gmail.com',
    from: 'yuval@Appsus.com',
    status: 'draft',
    isStarred: false,
  },
  // trash
  {
    id: utilService.makeId(),
    subject: 'You owe me money!',
    body: `25 shmeckles? I-I-I-I don't even know what that- what is that? Is that a lot? Now if you'll excuse me, I've got a quick solo adventure to go on and this one will not be directed by Ron Howard. Meeseeks don't usually have to exist for this long. It's gettin' weeeiiird. Burgertime!`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'JoeDoe@gmail.com',
    status: 'trash',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Work plan for next week',
    body: `make the logo a bit smaller because the logo is too big can you link the icons to my social media accounts? oh and please put pictures of cats everywhere we try your eye, but can you change everything? yet in an ideal world, we are a big name to have in your portfolio, so you are lucky to even be doing this for us can we have another option, and pass the mayo, appeal to the client, sue the vice president . Can we barter services? try making it a bit less blah we try your eye, but can you change everything?. Thanks for taking the time to make the website, but i already made it in wix i love it, but can you invert all colors?, can you remove my double chin on my business card photo? i don't like the way it looks i know this is the final release but can we add more features?. What you've given us is texty, we want sexy. Submit your meaningless business jargon to be used on the site! that's going to be a chunk of change use a kpop logo that's not a kpop logo! ugh.`,
    isRead: false,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'work-place@gmail.com',
    status: 'trash',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Cats facts',
    body: `Cats make plans to dominate world and then take a nap attack the dog then pretend like nothing happened toilet paper attack claws fluff everywhere meow miao french ciao litterbox for x eat and than sleep on your face or intrigued by the shower. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff bite nose of your human, pounce on unsuspecting person but swat turds around the house. Always hungry inspect anything brought into the house nya nya nyan enslave the hooman. Annoy owner until he gives you food say meow repeatedly until belly rubs, feels good slap the dog because cats rule for stinky `,
    isRead: true,
    sentAt: 1637774407228,
    to: 'yuval@Appsus.com',
    from: 'facts@walla.com',
    status: 'trash',
    isStarred: false,
  },
  // sent
  {
    id: utilService.makeId(),
    subject: 'Dogs or cats?',
    body: `Lick sellotape push your water glass on the floor litter kitter kitty litty little kitten big roar roar feed me stick butt in face, but kitty kitty for waffles but bury the poop bury it deep. Scoot butt on the rug run outside as soon as door open i shall purr myself to sleep miaow then turn around and show you my bum. Make plans to dominate world and then take a nap and sometimes switches in french and say "miaou" just because well why not make plans to dominate world and then take a nap. Cat snacks. Scamper human clearly uses close to one life a night no one naps that long so i revive by standing on chestawaken!.`,
    isRead: true,
    sentAt: 1637774407228,
    to: 'elonMusk@gmail.com',
    from: 'yuval@Appsus.com',
    status: 'sent',
    isStarred: false,
  },
  {
    id: utilService.makeId(),
    subject: 'Where is he?',
    body: `I need your full attention, Saul. Jesse Pinkman current whereabouts. The sooner you tell me, the sooner you can get back to whatever the hell this is exactly. Whoa, you are good right there. Now lets both get comfortable. Now when I say I'm looking for Pinkman, we both know why, don't we. And you pretending otherwise only wastes my time and serves to annoy me. I trust the hole in the desert I'd leave you in. Don't make me beat you 'til your legs don't work. Now tell me where to find him, you know it's the right thing. `,
    isRead: true,
    sentAt: 1637774407228,
    to: 'Saul1994@gmail.com',
    from: 'yuval@Appsus.com',
    status: 'sent',
    isStarred: false,
  },
];

function getDummyEmails() {
  return [...DUMMY_EMAILS];
}
